[project]
name = "cine-journal"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "django-environ>=0.12.1",
    "pillow>=12.1.1",
    "psycopg>=3.3.2",
]
